#!/usr/bin/env python3
from __future__ import annotations

import re
from pathlib import Path

RE_EVENT = re.compile(
    r'^\s*EV_EVENT\(\s*([A-Z0-9_]+)\s*,\s*([A-Z0-9_]+)\s*,\s*"([^"]*)"\s*\)\s*$'
)
RE_ACTOR = re.compile(
    r'^\s*EV_ACTOR\(\s*([A-Z0-9_]+)\s*,\s*([A-Z0-9_]+)\s*,\s*([A-Z0-9_]+)\s*,\s*([0-9]+U?)\s*,\s*"([^"]*)"\s*\)\s*$'
)
RE_ROUTE = re.compile(
    r'^\s*EV_ROUTE\(\s*([A-Z0-9_]+)\s*,\s*([A-Z0-9_]+)\s*\)\s*$'
)

ROOT = Path(__file__).resolve().parents[2]
CONFIG_DIR = ROOT / "config"
OUT_PATH = ROOT / "core" / "generated" / "include" / "ev" / "route_table_generated.h"


def read_catalog_lines(path: Path) -> list[str]:
    lines: list[str] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("//") or line.startswith("#"):
            continue
        lines.append(line)
    return lines


def parse_events(path: Path) -> list[str]:
    events: list[str] = []
    for line in read_catalog_lines(path):
        match = RE_EVENT.match(line)
        if match is None:
            raise ValueError(f"invalid event definition in {path}: {line}")
        events.append(match.group(1))
    return events


def parse_actors(path: Path) -> list[str]:
    actors: list[str] = []
    for line in read_catalog_lines(path):
        match = RE_ACTOR.match(line)
        if match is None:
            raise ValueError(f"invalid actor definition in {path}: {line}")
        actors.append(match.group(1))
    return actors


def parse_routes(path: Path) -> list[tuple[str, str]]:
    routes: list[tuple[str, str]] = []
    for line in read_catalog_lines(path):
        match = RE_ROUTE.match(line)
        if match is None:
            raise ValueError(f"invalid route definition in {path}: {line}")
        routes.append((match.group(1), match.group(2)))
    return routes


def validate_catalog(events: list[str], actors: list[str], routes: list[tuple[str, str]]) -> None:
    event_set = set(events)
    actor_set = set(actors)
    seen_routes: set[tuple[str, str]] = set()

    if len(event_set) != len(events):
        raise ValueError("duplicate event identifier in config/events.def")
    if len(actor_set) != len(actors):
        raise ValueError("duplicate actor identifier in config/actors.def")

    for event_name, actor_name in routes:
        if event_name not in event_set:
            raise ValueError(f"route references unknown event: {event_name}")
        if actor_name not in actor_set:
            raise ValueError(f"route references unknown actor: {actor_name}")
        route_key = (event_name, actor_name)
        if route_key in seen_routes:
            raise ValueError(f"duplicate route: {event_name} -> {actor_name}")
        seen_routes.add(route_key)


def group_routes_by_event(
    events: list[str],
    routes: list[tuple[str, str]],
) -> tuple[list[tuple[str, str]], dict[str, tuple[int, int]]]:
    grouped: list[tuple[str, str]] = []
    spans: dict[str, tuple[int, int]] = {}

    for event_name in events:
        start_index = len(grouped)
        for route in routes:
            if route[0] == event_name:
                grouped.append(route)
        spans[event_name] = (start_index, len(grouped) - start_index)

    return grouped, spans


def render_generated_header(
    events: list[str],
    routes: list[tuple[str, str]],
    spans: dict[str, tuple[int, int]],
) -> str:
    lines: list[str] = [
        "/* Auto-generated by tools/routegen/routegen.py.",
        " * Source of truth: config/routes.def.",
        " * Do not edit manually; run ./tools/fw routegen.",
        " */",
        "#ifndef EV_ROUTE_TABLE_GENERATED_H",
        "#define EV_ROUTE_TABLE_GENERATED_H",
        "",
        "#include \"ev/route_table.h\"",
        "",
        f"#define EV_ROUTE_TABLE_GENERATED_COUNT {len(routes)}U",
        "",
        "enum {",
    ]

    for event_name, actor_name in routes:
        lines.append(f"    EV_ROUTE_UNIQUE__{event_name}__{actor_name} = 1,")
    lines.extend(
        [
            "    EV_ROUTE_UNIQUE__SENTINEL = 0",
            "};",
            "",
            "static const ev_route_t k_ev_route_table_generated[] = {",
        ]
    )

    for event_name, actor_name in routes:
        lines.append(f"    {{ {event_name}, {actor_name} }},")
    lines.extend(
        [
            "};",
            "",
            "static const ev_route_span_t k_ev_route_spans_generated[EV_EVENT_COUNT] = {",
        ]
    )

    for event_name in events:
        start_index, count = spans[event_name]
        if count != 0:
            lines.append(f"    [{event_name}] = {{ {start_index}U, {count}U }},")

    lines.extend(
        [
            "};",
            "",
            "#endif /* EV_ROUTE_TABLE_GENERATED_H */",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    events = parse_events(CONFIG_DIR / "events.def")
    actors = parse_actors(CONFIG_DIR / "actors.def")
    source_routes = parse_routes(CONFIG_DIR / "routes.def")

    validate_catalog(events, actors, source_routes)
    grouped_routes, spans = group_routes_by_event(events, source_routes)

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(
        render_generated_header(events, grouped_routes, spans),
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
