#ifndef EV_ATNEL_AIR_BOARD_PROFILE_H
#define EV_ATNEL_AIR_BOARD_PROFILE_H
#include "ev/compiler.h"
#include "ev/oled_actor.h"
#include "ev/supervisor_actor.h"

#define EV_BOARD_PROFILE_TAG "ev_atnel"
#define EV_BOARD_PROFILE_NAME "atnel_air_esp_motherboard"
#define EV_BOARD_HAS_I2C0 1U
#define EV_BOARD_HAS_ONEWIRE0 1U
#define EV_BOARD_HAS_GPIO_IRQ 1U
#define EV_BOARD_HAS_DEEP_SLEEP_WAKE_GPIO16 0U
enum {
#define EV_BSP_PIN(name, gpio, desc) EV_BOARD_##name = (gpio),
#define EV_BSP_PIN_ANALOG(name, desc)
#include "pins.def"
#undef EV_BSP_PIN
#undef EV_BSP_PIN_ANALOG
};
#define EV_BOARD_I2C_SCL_GPIO       EV_BOARD_PIN_I2C0_SCL
#define EV_BOARD_I2C_SDA_GPIO       EV_BOARD_PIN_I2C0_SDA
#define EV_BOARD_ONEWIRE_GPIO       EV_BOARD_PIN_ONEWIRE0_DQ
#define EV_BOARD_IRQ_IR0_GPIO       EV_BOARD_PIN_OPTIONAL_IR0_DATA
#define EV_BOARD_IRQ_INT0_GPIO      EV_BOARD_PIN_OPTIONAL_INT0
#define EV_BOARD_RTC_ADDR_7BIT      0x68U
#define EV_BOARD_MCP23008_ADDR_7BIT 0x20U
#define EV_BOARD_OLED_ADDR_7BIT     0x3CU
#define EV_BOARD_OLED_CONTROLLER    EV_OLED_CONTROLLER_SSD1306
#define EV_BOARD_RTC_SQW_LINE_ID    0U
#define EV_BOARD_RUNTIME_HARDWARE_PRESENT_MASK \
    (EV_SUPERVISOR_HW_MCP23008 | EV_SUPERVISOR_HW_RTC | EV_SUPERVISOR_HW_OLED | EV_SUPERVISOR_HW_DS18B20)
#define EV_BOARD_SUPERVISOR_REQUIRED_MASK \
    (EV_SUPERVISOR_HW_MCP23008 | EV_SUPERVISOR_HW_RTC)
#define EV_BOARD_SUPERVISOR_OPTIONAL_MASK \
    (EV_SUPERVISOR_HW_OLED | EV_SUPERVISOR_HW_DS18B20)

/*
 * Hardware-in-the-loop I2C zero-heap test policy.  Fault GPIOs are disabled by
 * default because they require an external open-drain-safe fixture wired to the
 * I2C bus or IRQ input.  Override these macros from the target build or board
 * lab profile only when the fixture is present.
 */
#ifndef EV_BOARD_HIL_I2C_RTC_READ_ITERATIONS
#define EV_BOARD_HIL_I2C_RTC_READ_ITERATIONS 1000U
#endif
#ifndef EV_BOARD_HIL_I2C_MCP_RW_ITERATIONS
#define EV_BOARD_HIL_I2C_MCP_RW_ITERATIONS 1000U
#endif
#ifndef EV_BOARD_HIL_I2C_OLED_PARTIAL_FLUSHES
#define EV_BOARD_HIL_I2C_OLED_PARTIAL_FLUSHES 16U
#endif
#ifndef EV_BOARD_HIL_I2C_OLED_FULL_FLUSHES
#define EV_BOARD_HIL_I2C_OLED_FULL_FLUSHES 1U
#endif
#ifndef EV_BOARD_HIL_I2C_IRQ_FLOOD_TRANSACTIONS
#define EV_BOARD_HIL_I2C_IRQ_FLOOD_TRANSACTIONS 128U
#endif
#ifndef EV_BOARD_HIL_I2C_MISSING_ADDR_7BIT
#define EV_BOARD_HIL_I2C_MISSING_ADDR_7BIT 0x55U
#endif
#ifndef EV_BOARD_HIL_I2C_SDA_FAULT_GPIO
#define EV_BOARD_HIL_I2C_SDA_FAULT_GPIO (-1)
#endif
#ifndef EV_BOARD_HIL_I2C_SCL_FAULT_GPIO
#define EV_BOARD_HIL_I2C_SCL_FAULT_GPIO (-1)
#endif
#ifndef EV_BOARD_HIL_IRQ_FLOOD_OUTPUT_GPIO
#define EV_BOARD_HIL_IRQ_FLOOD_OUTPUT_GPIO (-1)
#endif
#ifndef EV_BOARD_HIL_IRQ_FLOOD_LINE_ID
#define EV_BOARD_HIL_IRQ_FLOOD_LINE_ID 0U
#endif
#ifndef EV_BOARD_HIL_ONEWIRE_READS
#define EV_BOARD_HIL_ONEWIRE_READS 4U
#endif

#endif /* EV_ATNEL_AIR_BOARD_PROFILE_H */
